CREATE TABLE STUDENT (ID INT NOT NULL, 
Grade_Level INT, 
Grade_Modified_Date DATE NOT NULL, 
Registration_Date DATE, 
Gender VARCHAR(50), 
Race VARCHAR(50), 
isCurrent BOOLEAN, 
Days_Missed INT, 
PRIMARY KEY(ID)); 


CREATE TABLE CUM_GPA(ID INT NOT NULL, 
GPA FLOAT CHECK (GPA > 0.0 AND GPA <= 4.0), 
GPA_Entry_Date DATE, 
FOREIGN KEY(ID) REFERENCES STUDENT(ID));


CREATE TABLE PAST_STUDENT(ID INT NOT NULL, 
Reason VARCHAR(100), 
Leave_Date DATE, 
FOREIGN KEY(ID) REFERENCES STUDENT(ID));


CREATE TABLE UN_CUM_GPA(ID INT NOT NULL, 
GPA FLOAT CHECK (GPA > 0.0 AND GPA <= 4.0), 
GPA_Entry_Date DATE, 
FOREIGN KEY(ID) REFERENCES STUDENT(ID));


CREATE TABLE REFERRALS(ID INT NOT NULL, 
Referral_Date DATE, 
Type VARCHAR(50), 
Description VARCHAR(250), 
FOREIGN KEY(ID) REFERENCES STUDENT(ID));


CREATE TABLE SCHOOL(Name VARCHAR(100), 
PRIMARY KEY(Name));


CREATE TABLE ATTENDS(Start_Date DATE NOT NULL, 
End_Date DATE, 
Student_ID INT NOT NULL, 
School_Name VARCHAR(100) NOT NULL, 
FOREIGN KEY (Student_ID) REFERENCES STUDENT(ID),
FOREIGN KEY(School_Name) REFERENCES SCHOOL(Name));
